### ISSUE TITLE
8 sec audio file takes a very long time to process

### ISSUE THREAD

**Issue by GrahamboJangles** [mosheman5/DNP#1]
I'm trying to denoise an 8 second audio file and it's going to take me about 2 hours to process with a GTX 1070. Is this normal? It seems a bit impractical, considering how short the audio is. It also doesn't seem as if I can pause and resume the training, if that is what it is doing.

**Comment by mosheman5** [comment]
It does takes few minutes on GTX1080Ti.
Perhaps you can try changing the parameters for less iterations (5000 --> 1000).
