### ISSUE TITLE
Processing time is long 

### ISSUE THREAD

**Issue by TeerathChandani** [mosheman5/DNP#5]
Since I have 5 sec audio file, I want to clean noise from audio. It is taking more time, although I reduced iterations. 

I do not think, it will work in real time? 
Why it takes long time? 

Thanks,

**Comment by mosheman5** [comment]
The method is not working in real time, and I wouldn't recommend using it for this purpose.
The core idea and contribution of our paper is to present the strong unsupervised priors of deep neural networks in the audio domain.
I hope that in the future we will find a way for utilizing those priors into a fast feed-forward algorithms, but further research has to be done both in image and audio domains.

**Comment by TeerathChandani** [comment]
Ok thanks,
