### ISSUE TITLE
Source file sample rate considerations

### ISSUE THREAD

**Issue by dister520** [mosheman5/DNP#6]
Interesting project, I was wondering if there is a way to support 48 khz sample rate files. Trying the files the issue I see is that it only support 4s 16k, 16-bit files.

**Comment by mosheman5** [comment]
Thanks and sorry for the late reply!
The work was never tested on 48kHz so no results are guaranteed, having said that there is no dependency on sample rate either in the algorithm or in the code.
The only parameter I would play with is the nfft which might have and influence on the results.
